model:
  conv_layer_count: 5
  conv_layer_kernel: 3
  conv_layer_filters: 32

  layout: "NDHWC"
  script: False
  cuda_graph: True 
  #cuda_graph: False 

  training:
    target_score: 0.124
    dropout_rate: 0.5
    weight_decay: 0

    momentum: 0.9
    amp: True 

    optimizer: "fixed_sgd"

    lr_sched:
      lr: 0.004
      init_lr: 0.001
      warmup_epochs: 2

      decay_steps:
        - 32
        - 64

      decay_values:
        - 0.5
        - 0.25

    train_epochs: 10

data:
  batch_size: 1
  train_samples: 256
  valid_samples: 64
  dataset: "cosmoflow_npy"
  
  apply_log: True
  shuffle: True
  preshuffle: False
  shard_type: "local"
  shard_multiplier: 1

  root_dir: "/work/cosmoflow/cosmo_pt_small/"
  stage: "/tmp"
  stage_mode: "sequential"
  #stage_mode: "process"
  #stage_mode: "thread" not working
  stage_workers: 4
  sample_shape: [128, 128, 128, 4]
  target_shape: [4]

  dali_threads: 4
  data_layout: "NDHWC"

log:
    timestamp: "0"
    experiment_id: "1"
mpi:
    local_rank: 0
    local_size:  1
   

profile: False